# Generated by Django 5.1 on 2024-08-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='onlince course', max_length=50),
        ),
    ]
